spring:
  application:
    name: pay-service
  datasource:
    url: jdbc:mysql://localhost:3306/paydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
